{
  "clair":{
    "status": "scanned",
    "data": {
      "Layer": {
        "Name": "sha256:24c0a33d297f04022bf603ad887a7466cdff908caf67794d7acc2e405650e796",
        "ParentName": "",
        "NamespaceName": "",
        "IndexedByVersion": 4,
        "Features": [
          {
            "Name": "py3-pip",
            "VersionFormat": "",
            "NamespaceName": "",
            "AddedBy": "sha256:f2b173ea7ea4f29c66496ee10fd17acd7c4bfec05fcfb34bc0682de4ced2e059",
            "Version": "20.3.4-r1",
            "Vulnerabilities": []
          },
          {
            "Name": "pip",
            "VersionFormat": "",
            "NamespaceName": "",
            "AddedBy": "sha256:f2b173ea7ea4f29c66496ee10fd17acd7c4bfec05fcfb34bc0682de4ced2e059",
            "Version": "20.3.4",
            "Vulnerabilities": [
              {
                "Severity": "Medium",
                "NamespaceName": "pyupio",
                "Link": "",
                "FixedBy": "",
                "Description": "Pip version 21.1 updates its dependency \"urllib3\" to 1.26.4 to fix CVE-2021-28363.",
                "Name": "pyup.io-40291 (CVE-2021-28363)",
                "Metadata": {
                  "UpdatedBy": "pyupio",
                  "RepoName": "pypi",
                  "RepoLink": "https://pypi.org/simple",
                  "DistroName": "",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
                      "Score": 6.5
                    }
                  }
                }
              },
              {
                "Severity": "Unknown",
                "NamespaceName": "pyupio",
                "Link": "",
                "FixedBy": "",
                "Description": "Pip version 21.1 stops splitting on unicode separators in git references, which could be maliciously used to install a different revision on the repository. \r\nhttps://github.com/pypa/pip/issues/9827",
                "Name": "pyup.io-42218 (PVE-2021-42218)",
                "Metadata": {
                  "UpdatedBy": "pyupio",
                  "RepoName": "pypi",
                  "RepoLink": "https://pypi.org/simple",
                  "DistroName": "",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "",
                      "Score": ""
                    }
                  }
                }
              },
              {
                "Severity": "Unknown",
                "NamespaceName": "pyupio",
                "Link": "",
                "FixedBy": "1.34.1-r3",
                "Description": "TEST Patched vulnerability",
                "Name": "pyup.io-42219 (PVE-2021-42219)",
                "Metadata": {
                  "UpdatedBy": "pyupio",
                  "RepoName": "pypi",
                  "RepoLink": "https://pypi.org/simple",
                  "DistroName": "",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "",
                      "Score": ""
                    }
                  }
                }
              },
              {
                "Severity": "Negligible",
                "NamespaceName": "pyupio",
                "Link": "",
                "FixedBy": "1.34.1-r4",
                "Description": "TEST Negligible Patched vulnerability",
                "Name": "pyup.io-42213 (PVE-2021-42213)",
                "Metadata": {
                  "UpdatedBy": "pyupio",
                  "RepoName": "pypi",
                  "RepoLink": "https://pypi.org/simple",
                  "DistroName": "",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "",
                      "Score": ""
                    }
                  }
                }
              },
              {
                "Severity": "Critical",
                "NamespaceName": "pyupio",
                "Link": "",
                "FixedBy": "",
                "Description": "Pip version 21.1 updates its dependency 'urllib3' to v1.26.4 to include a security fix.",
                "Name": "pyup.io-40291 (CVE-2021-28363)",
                "Metadata": {
                  "UpdatedBy": "pyupio",
                  "RepoName": "pypi",
                  "RepoLink": "https://pypi.org/simple",
                  "DistroName": "",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
                      "Score": 6.5
                    }
                  }
                }
              },
              {
                "Severity": "Low",
                "NamespaceName": "pyupio",
                "Link": "",
                "FixedBy": "",
                "Description": "Pip version 21.1 includes a fix for CVE-2021-3572: A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity.\r\nhttps://bugzilla.redhat.com/show_bug.cgi?id=1962856",
                "Name": "pyup.io-42559 (CVE-2021-3572)",
                "Metadata": {
                  "UpdatedBy": "pyupio",
                  "RepoName": "pypi",
                  "RepoLink": "https://pypi.org/simple",
                  "DistroName": "",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
                      "Score": 5.7
                    }
                  }
                }
              },
              {
                "Severity": "Low",
                "NamespaceName": "pyupio",
                "Link": "",
                "FixedBy": "1.34.1-r3",
                "Description": "TEST patched vulnerability",
                "Name": "pyup.io-42556(CVE-2021-3575)",
                "Metadata": {
                  "UpdatedBy": "pyupio",
                  "RepoName": "pypi",
                  "RepoLink": "https://pypi.org/simple",
                  "DistroName": "",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
                      "Score": 5.7
                    }
                  }
                }
              },
              {
                "Severity": "Medium",
                "NamespaceName": "pyupio",
                "Link": "",
                "FixedBy": "",
                "Description": "another medium level CVE, to test if multiple CVEs per RPM are reported correctly",
                "Name": "pyup.io-40291 (CVE-another-cve-for-the-test)",
                "Metadata": {
                  "UpdatedBy": "pyupio",
                  "RepoName": "pypi",
                  "RepoLink": "https://pypi.org/simple",
                  "DistroName": "",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
                      "Score": 6.5
                    }
                  }
                }
              },
              {
                "Severity": "Critical",
                "NamespaceName": "pyupio",
                "Link": "",
                "FixedBy": "",
                "Description": "Pip 21.1 updates its dependency 'urllib3' to v1.26.4 due to security issues. (TEST that the same CVE is not reported twice)",
                "Name": "pyup.io-40291 (CVE-2021-28363)",
                "Metadata": {
                  "UpdatedBy": "pyupio",
                  "RepoName": "pypi",
                  "RepoLink": "https://pypi.org/simple",
                  "DistroName": "",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
                      "Score": 6.5
                    }
                  }
                }
              },
              {
                "Severity": "Critical",
                "NamespaceName": "pyupio",
                "Link": "",
                "FixedBy": "1.34.1-r3",
                "Description": "Pip 21.1 updates its dependency 'urllib3' to v1.26.4 due to security issues. (TEST an patched vulnerability)",
                "Name": "pyup.io-40291 (CVE-2021-28367)",
                "Metadata": {
                  "UpdatedBy": "pyupio",
                  "RepoName": "pypi",
                  "RepoLink": "https://pypi.org/simple",
                  "DistroName": "",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
                      "Score": 6.5
                    }
                  }
                }
              }
            ]
          },
          {
            "Name": "busybox",
            "VersionFormat": "",
            "NamespaceName": "",
            "AddedBy": "sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3",
            "Version": "1.34.1-r3",
            "Vulnerabilities": [
              {
                "Severity": "Medium",
                "NamespaceName": "alpine-main-v3.15-updater",
                "Link": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=ALPINE-13661",
                "FixedBy": "1.34.1-r5",
                "Description": "",
                "Name": "ALPINE-13661",
                "Metadata": {
                  "UpdatedBy": "alpine-main-v3.15-updater",
                  "RepoName": null,
                  "RepoLink": null,
                  "DistroName": "Alpine Linux",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "",
                      "Score": ""
                    }
                  }
                }
              }
            ]
          },
          {
            "Name": "zlib",
            "VersionFormat": "",
            "NamespaceName": "",
            "AddedBy": "sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3",
            "Version": "1.2.11-r3",
            "Vulnerabilities": [
              {
                "Severity": "High",
                "NamespaceName": "alpine-main-v3.15-updater",
                "Link": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-25032",
                "FixedBy": "1.2.12-r0",
                "Description": "",
                "Name": "CVE-2018-25032",
                "Metadata": {
                  "UpdatedBy": "alpine-main-v3.15-updater",
                  "RepoName": null,
                  "RepoLink": null,
                  "DistroName": "Alpine Linux",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                      "Score": 7.5
                    }
                  }
                }
              }
            ]
          },
          {
            "Name": "zlib",
            "VersionFormat": "",
            "NamespaceName": "",
            "AddedBy": "sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3",
            "Version": "1.2.11-r3-different",
            "Vulnerabilities": [
              {
                "Severity": "High",
                "NamespaceName": "alpine-main-v3.15-updater",
                "Link": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-25032",
                "FixedBy": "1.2.12-r0",
                "Description": "TEST: The same vulnerability, but different version of package",
                "Name": "CVE-2018-25032",
                "Metadata": {
                  "UpdatedBy": "alpine-main-v3.15-updater",
                  "RepoName": null,
                  "RepoLink": null,
                  "DistroName": "Alpine Linux",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                      "Score": 7.5
                    }
                  }
                }
              }
            ]
          },
          {
            "Name": "zlib",
            "VersionFormat": "",
            "NamespaceName": "",
            "AddedBy": "sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3",
            "Version": "1.2.11-r3",
            "Vulnerabilities": [
              {
                "Severity": "High",
                "NamespaceName": "alpine-main-v3.15-updater",
                "Link": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-25032",
                "FixedBy": "",
                "Description": "An unpatched vulnerability",
                "Name": "CVE-2018-25045",
                "Metadata": {
                  "UpdatedBy": "alpine-main-v3.15-updater",
                  "RepoName": null,
                  "RepoLink": null,
                  "DistroName": "Alpine Linux",
                  "DistroVersion": "",
                  "NVD": {
                    "CVSSv3": {
                      "Vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                      "Score": 7.5
                    }
                  }
                }
              }
            ]
          }
        ]
      }
    }
  }
}
